Comment out invoke-action step

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -22,10 +22,10 @@ runs:
         echo -n "${{inputs.string-val}}"
         
 
-    - id: invoke-action-1
-      name: invoke-action
-      uses: docker://golang:1.20.3-alpine3.17
-      shell: sh
-      run: |
-        echo "Exiting due to error: <your message here>" >&2
-        exit 1
+    # - id: invoke-action-1
+    #   name: invoke-action
+    #   uses: docker://golang:1.20.3-alpine3.17
+    #   shell: sh
+    #   run: |
+    #     echo "Exiting due to error: <your message here>" >&2
+    #     exit 1
